### ISSUE TITLE
Jade-Templates

### ISSUE THREAD

**Issue by ronnyhartenstein** [CodeforChemnitz/presentation#2]
Statt sich mit HTML-Tags rumzuärgern kann man auch Hippster-mäßig Jade-Templates nutzen.
Da gibts auch ein tolles Grunt-Plugin https://www.npmjs.com/package/grunt-reveal-jade das das alles gleich macht. Ich wäre für Umstellung und würde es auch selbst tun (und alle momentanen Inhalte einfach mitnehmen. (natürlich erstmal in einen eigenen Branch).

**Comment by MorrisJobke** [comment]
Nach dem Vortrag heute :)
